### ISSUE TITLE
Missing 3 undetermined_indices files in 2bRAD_Dec15

### ISSUE THREAD

**Issue by ksil91** [RobertsLab/project-olympia.oyster-genomic#13]
There are only 2 undetermined_indices.fastq files in the 2bRAD_Dec15 folder. There should be 5 total- one for each lane sequenced. I suspect the issue is that these files have uniformative names regarding the flowcell they came off of (all files are named either lane1_Undetermined_L001_R1_001.fastq.gz or lane2_Undetermined_L001_R1_001.fastq.gz). Need to go back to Genewiz ftp site, download each undetermined file and rename it so we can tell which library/flowcell they came from.

**Comment by kubu4** [comment]
We have the full Genewiz file set, with data sheets & all of the raw Illumina output files, so no need to re-download, if desired. Before I last left lab, I was waiting on tarball gzip compression to finish for these files. Find the tarball in my home folder on Owl. Feel free to copy over to Owl/web for easier access. Might be a food idea to create MD5 before copying, due to large file size.

**Comment by ksil91** [comment]
Are the files in the folder Project_BS1511196_R2_01 in your home directory the ones from the 2nd demultiplexing? They are dated from Dec 24, 2015 which is before we corrected the barcodes.

**Comment by kubu4** [comment]
Thanks for catching this, @ksil91! Turns out, the FASTQ files labeled with "undetermined" do not have unique names across the different lanes. As such, when I used bash to find and move just the FASTQ files, the "undetermined" filenames overwrote the previous ones. So, we only ended up with two FASTQ files representing the undetermined reads.

Re-downloading the entire project file. Will post here when it is finished.

**Comment by kubu4** [comment]
Alrighty, I've taken care of this issue. Thanks again, @ksil91! There were a total of 17 FASTQ files labelled as "undetermined". I relabelled each of them to have unique filenames, reflecting the higher level folders they were stored in. 

These freshly renamed files have been copied over to [Owl/O_lurida/2bRAD_Dec2015](http://owl.fish.washington.edu/nightingales/O_lurida/2bRAD_Dec2015/).
