### ISSUE TITLE
Add SRA numbers for Illumina Genome Seq Data

### ISSUE THREAD

**Issue by sr320** [RobertsLab/project-olympia.oyster-genomic#26]
Please add SRA links/accessions for Illumina data on wiki
https://github.com/RobertsLab/project-olympia.oyster-genomic/wiki/Genome-sequencing-September-2015

**Comment by kubu4** [comment]
These haven't been published. Should I change release date to tomorrow (earliest date I can enter)?

**Comment by sr320** [comment]
Sure- but I thought I saw four entries in SRA when searching for GBS that
indicated genome sequencing?

**Comment by kubu4** [comment]
Probably this? [PRJNA316624](https://www.ncbi.nlm.nih.gov/bioproject/PRJNA316624)

OMG! The SRA is such a total cluster! In the "Submission Dashboard" view, it looks like this hasn't been published (because it's waiting on two additional files).

However, the four sets of FASTQ files that are complete have actually been published!!!



![submission___submit___sequence_read_archive___ncbi_nlm_nih_v_0_7_2](https://cloud.githubusercontent.com/assets/4514104/25185169/7bb6675a-24d1-11e7-8262-a12862ffdd72.png)

**Comment by sr320** [comment]
Next submission- might want to try EBI

**Comment by kubu4** [comment]
Uploading remaining two files. Links to all other files have been added. Will add remaining links once published.
